Feature/ltbi results processing
ihmeuw/vivarium_csu_ltbi pull request #92
Opened 2020-02-04 23:26 UTC by yaqi7

Here is the updated script which changed CI to percentile, assign 0 to NA (NA from 0 denominator), and merged 100 and 10 file together. Please let me know if there is any question. Thank you
https://github.com/ihmeuw/vivarium_csu_ltbi/blob/feature/ltbi_results_processing/src/vivarium_csu_ltbi/tools/ltbi_result_process.py

2020-02-11 04:51 UTC, aflaxman requested changes

2020-02-11 04:51 UTC, aflaxman commented on src/vivarium_csu_ltbi/tools/number_and_percent_under5_with_hh_AcTB.py
> +    df = pd.merge(df1.reset_index(), df2.reset_index(), on = ["input_draw_number", "random_seed", "ltbi_treatment_scale_up.scenario"], how = 'outer')
Let's change this line together.  I still have a different idea on how to combine df1 and df2.

2020-02-11 19:42 UTC, halfhorst commented on src/vivarium_csu_ltbi/tools/ltbi_result_process.py
> +    'ethiopia_end_100': result_dir + 'updated-input-data-end-100/ethiopia/2020_01_03_14_22_51/output.hdf',
there are more recent results than this now

2020-02-11 19:46 UTC, halfhorst commented
I'm going to work on incorporating this into the results processing command so that it is automatically generated with the other tables. I'll tag you both on the PR when I'm done

2020-02-11 19:55 UTC, yaqi7 commented
> I'm going to work on incorporating this into the results processing command so that it is automatically generated with the other tables. I'll tag you both on the PR when I'm done

Thank you Cody, I am updating the script using add function to replace merge and will push the updated one in a few minutes.

2020-02-11 20:15 UTC, yaqi7 commented
> I'm going to work on incorporating this into the results processing command so that it is automatically generated with the other tables. I'll tag you both on the PR when I'm done

@halfhorst Thank you Cody, I did a little change of replacing merge function with add function. Following is the most recent version:
https://github.com/ihmeuw/vivarium_csu_ltbi/blob/bee0f3d3769280d32e4eb8ae44dc66b49d48ec76/src/vivarium_csu_ltbi/tools/ltbi_result_process.py

2020-02-13 22:50 UTC, halfhorst commented
I believe this is covered by #101, and the new make_results produces 'averted' information for the final tables as well

2020-02-13 22:50 UTC, closed without merging